### ISSUE TITLE
给出的文档示例无法查看源码，希望增加在展示页直接查看实现方式

### ISSUE THREAD

**Issue by zuoliang0** [fanruan/fineui#3]
http://fanruan.coding.me/fineui/
![image](https://user-images.githubusercontent.com/8434253/48777222-00e27900-ed0d-11e8-8741-5aeea69d61ce.png)

这个示例中，所有页面的源码是写到一个文件的，点击对应的组件后无法方便的好看到对应的实现，建议使用iframe实现，可以方便快速查看和学习。

感谢

**Comment by MrErHu** [comment]
@zuoliang0 
非常感谢对FineUI的关注，FineUI孵化于FineBI内部框架。对外[FineUI官方文档](http://fanruan.coding.me/fineui-doc)正在进一步完善中，届时将包含各个控件具体的使用方法和Demo实例。

**Comment by gittz** [comment]
http://fanruan.design希望能帮到你

**Comment by zuoliang0** [comment]
对于每一个控件的事件列表是否能提供一下，现在没有提供这个部分

**Comment by gittz** [comment]
> 对于每一个控件的事件列表是否能提供一下，现在没有提供这个部分

感谢你的支持，文档中已经提供事件支持了
