### ISSUE TITLE
按照UI实例，树形结构的表格渲染会报找不到element

### ISSUE THREAD

**Issue by shiduobin** [fanruan/fineui#4]
![image](https://user-images.githubusercontent.com/26728144/100597567-92434780-3338-11eb-91bc-79b9b83d92d4.png)

**Comment by taiyangzaitianshang** [comment]
https://fanruan.design/doc.html?post=07fb1710f6是这个文档中的表格吗？
贴下代码看看

**Comment by taiyangzaitianshang** [comment]
https://fanruan.design/doc.html?post=07fb1710f6是这个文档中的表格吗？
贴下代码看看

**Comment by shiduobin** [comment]
` var items = [
        {
          children: [
            {
              text: "节点1",
              children: [
                {
                  text: "子节点1",
                  children: [
                    {
                      text: "叶节点1",
                      values: [
                        { text: 11 },
                        { text: 12 },
                        { text: 11 },
                        { text: 12 },
                        { text: 11 },
                        { text: 12 },
                        { text: 112 },
                      ],
                    },
                    {
                      text: "叶节点2",
                      values: [
                        { text: 21 },
                        { text: 22 },
                        { text: 21 },
                        { text: 22 },
                        { text: 21 },
                        { text: 22 },
                        { text: 122 },
                      ],
                    },
                  ],
                  values: [
                    { text: 101 },
                    { text: 102 },
                    { text: 101 },
                    { text: 102 },
                    { text: 101 },
                    { text: 102 },
                    { text: 1102 },
                  ],
                },
                {
                  text: "子节点2",
                  children: [
                    {
                      text: "叶节点3",
                      values: [
                        { text: 31 },
                        { text: 32 },
                        { text: 31 },
                        { text: 32 },
                        { text: 31 },
                        { text: 32 },
                        { text: 132 },
                      ],
                    },
                    {
                      text: "叶节点4",
                      values: [
                        { text: 41 },
                        { text: 42 },
                        { text: 41 },
                        { text: 42 },
                        { text: 41 },
                        { text: 42 },
                        { text: 142 },
                      ],
                    },
                  ],
                  values: [
                    { text: 201 },
                    { text: 202 },
                    { text: 201 },
                    { text: 202 },
                    { text: 201 },
                    { text: 202 },
                    { text: 1202 },
                  ],
                },
                {
                  text: "子节点3",
                  children: [
                    {
                      text: "叶节点5",
                      values: [
                        { text: 51 },
                        { text: 52 },
                        { text: 51 },
                        { text: 52 },
                        { text: 51 },
                        { text: 52 },
                        { text: 152 },
                      ],
                    },
                  ],
                  values: [
                    { text: 301 },
                    { text: 302 },
                    { text: 301 },
                    { text: 302 },
                    { text: 301 },
                    { text: 302 },
                    { text: 1302 },
                  ],
                },
              ],
              values: [
                { text: 1001 },
                { text: 1002 },
                { text: 1001 },
                { text: 1002 },
                { text: 1001 },
                { text: 1002 },
                { text: 11002 },
              ],
            },
            {
              text: "节点2",
              values: [
                { text: 2001 },
                { text: 2002 },
                { text: 2001 },
                { text: 2002 },
                { text: 2001 },
                { text: 2002 },
                { text: 12002 },
              ],
            },
          ],
          values: [
            { text: 12001 },
            { text: 12002 },
            { text: 12001 },
            { text: 12002 },
            { text: 12001 },
            { text: 12002 },
            { text: 112002 },
          ],
        },
      ];
      var header = [
        {
          text: "header1",
        },
        {
          text: "header2",
        },
        {
          text: "header3",
        },
        {
          text: "金额",
          tag: 1,
        },
        {
          text: "金额",
          tag: 2,
        },
        {
          text: "金额",
          tag: 3,
        },
        {
          text: "金额",
          tag: 4,
        },
        {
          text: "金额",
          tag: 5,
        },
        {
          text: "金额",
          tag: 6,
        },
        {
          text: "金额",
          tag: 7,
        },
      ];
      var crossHeader = [
        {
          text: "cross1",
        },
        {
          text: "cross2",
        },
      ];
      var crossItems = [
        {
          children: [
            {
              text: "节点1",
              children: [
                {
                  text: "子节点1",
                },
                {
                  text: "子节点2",
                },
              ],
              values: [0],
            },
            {
              text: "节点2",
              children: [
                {
                  text: "子节点3",
                },
                {
                  text: "子节点4",
                },
              ],
              values: [0],
            },
          ],
          values: [0],
        },
      ];
      BI.createWidget({
        element: "#container",
        type: "bi.tree_table",
        el: {
          type: "bi.adaptive_table",
          el: {
            type: "bi.resizable_table",
            el: {
              type: "bi.collection_table",
              mergeRule: function (col1, col2) {
                return BI.isEqual(col1, col2);
              },
            },
          },
        },
        width: 1200,
        height: 400,
        isNeedResize: true,
        isNeedFreeze: true,
        isNeedMerge: true,
        freezeCols: [0, 1, 2],
        mergeCols: [0, 1, 2],
        minColumnSize: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
        columnSize: [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
        header: header,
        items: items,
        crossHeader: crossHeader,
        crossItems: crossItems,
      });`

**Comment by shiduobin** [comment]
感觉像bi.resizable_table这一层组件的问题，如果不加这一层是好的，但是不能拖拽表格

**Comment by taiyangzaitianshang** [comment]
![image](https://user-images.githubusercontent.com/8625315/100999477-cb2d2780-3597-11eb-828a-676a3c97128a.png)
你好，试了你的代码，是没有问题的，那个报错可能在于你createWidget时候指定的element不存在

**Comment by taiyangzaitianshang** [comment]
的确是resize_table的问题，生命周期不规范的原因导致的问题。现已修复，重新加载https://fanruan.design/fineui/materials.bundle.min.js
试试看
